services:
  twitchat:
    build:
      context: .
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3018/api"]
      interval: 30s
      timeout: 5s
      start_period: 10s
      retries: 3
    image: twitchat:latest
    ports:
      - "3018:3018"
    restart: unless-stopped
    volumes:
      - ./data:/opt/twitchat/data
